# This workflow generates documentation for tv channels automatically based
# on what's in the `cable` directory.
#
# See `./scripts/generate_cable_docs.py`
#
# The script will automatically pick up any corresponding demo image files
# in the `assets/channels` directory that match the channel names.
name: Generate Cable Docs
permissions:
  contents: write
on:
  pull_request:
    paths:
      - 'cable/**'
      - 'assets/channels/**'
  workflow_dispatch:
jobs:
  generate-docs:
    name: Generate Cable Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Python
        run: uv python install
      - name: create venv
        run: uv venv && source .venv/bin/activate
      - name: Install dependencies
        run: python -m pip install toml
      - name: Generate documentation
        run: python scripts/generate_cable_docs.py
      - name: if docs changed, create a PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'docs(cable): update channel documentation (auto)'
          title: 'docs(cable): update channel documentation (auto)'
          body: 'This PR was created by a GitHub Action to update the channel documentation.'
          branch: bot/auto-cable-docs-update
          base: main
          add-paths: docs/community_channels
          delete-branch: true
          signoff: true
